### ISSUE TITLE
可否将此博客主题移植到Jekyll上

### ISSUE THREAD

**Issue by yufeiminds** [lepture/lepture.com#2]
从大二开始Follow您的博客，今年大三，非常喜欢这样的风格，以及对W3C语义化(tag, class)的支持。希望把大部分的代码map到自己的博客上，并且注明您为作者，望得到您的首肯。

**Comment by lepture** [comment]
有一个稍早一点的版本 https://github.com/lepture/jekyll-vision

如果要做移植的话，建议用最新的 https://github.com/lepture/yue.css

**Comment by yufeiminds** [comment]
忘记关闭这个Issue了，十万分感谢，:)
