### ISSUE TITLE
how to build and preview this blog?

### ISSUE THREAD

**Issue by pigletfly** [lepture/lepture.com#4]
I see ```writeup``` and  ```ghp-import``` in Makefile,what's it stands for ? Your blog style is awesome,and want to build a blog based on your theme.Is it hosted on Github pages?

**Comment by lepture** [comment]
`writeup` is my own static site generator.

You can try: https://github.com/lepture/jekyll-vision

**Comment by pigletfly** [comment]
👌,thanks.
